const express = require('express');
const http = require('http');
const { Server } = require('socket.io');
const path = require('path');

const app = express();
const server = http.createServer(app);
const io = new Server(server);

app.use(express.static(path.join(__dirname, 'public')));

const users = {};

io.on('connection', (socket) => {
    console.log(`Bir kullanıcı bağlandı: ${socket.id}`);

        socket.on('join_chat', (username) => {
                users[socket.id] = {
                            username: username,
                                        friends: [],
                                                    requests: []
                                                            };
                                                                    updateUserList();
                                                                        });

                                                                            socket.on('send_friend_request', (targetUsername) => {
                                                                                    const sender = users[socket.id];
                                                                                            let targetSocketId = null;

                                                                                                    for (let id in users) {
                                                                                                                if (users[id].username === targetUsername) {
                                                                                                                                targetSocketId = id;
                                                                                                                                                break;
                                                                                                                                                            }
                                                                                                                                                                    }

                                                                                                                                                                            if (targetSocketId && sender) {
                                                                                                                                                                                        const target = users[targetSocketId];
                                                                                                                                                                                                    if (!target.requests.includes(sender.username) && target.username !== sender.username) {
                                                                                                                                                                                                                    target.requests.push(sender.username);
                                                                                                                                                                                                                                    io.to(targetSocketId).emit('friend_request_received', sender.username);
                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                socket.on('accept_friend_request', (requesterUsername) => {
                                                                                                                                                                                                                                                                        const accepter = users[socket.id];
                                                                                                                                                                                                                                                                                let requesterSocketId = null;

                                                                                                                                                                                                                                                                                        for (let id in users) {
                                                                                                                                                                                                                                                                                                    if (users[id].username === requesterUsername) {
                                                                                                                                                                                                                                                                                                                    requesterSocketId = id;
                                                                                                                                                                                                                                                                                                                                    break;
                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                if (requesterSocketId && accepter) {
                                                                                                                                                                                                                                                                                                                                                                            const requester = users[requesterSocketId];

                                                                                                                                                                                                                                                                                                                                                                                        if (!accepter.friends.includes(requester.username)) accepter.friends.push(requester.username);
                                                                                                                                                                                                                                                                                                                                                                                                    if (!requester.friends.includes(accepter.username)) requester.friends.push(accepter.username);

                                                                                                                                                                                                                                                                                                                                                                                                                accepter.requests = accepter.requests.filter(u => u !== requesterUsername);

                                                                                                                                                                                                                                                                                                                                                                                                                            socket.emit('friend_list_update', accepter.friends);
                                                                                                                                                                                                                                                                                                                                                                                                                                        io.to(requesterSocketId).emit('friend_list_update', requester.friends);
                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                updateUserList();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                socket.on('send_private_message', (data) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const sender = users[socket.id];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (!sender) return;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        for (let id in users) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (users[id].username === data.recipient) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    io.to(id).emit('receive_private_message', {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        sender: sender.username,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            message: data.message,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            socket.on('disconnect', () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    delete users[socket.id];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            updateUserList();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    console.log(`Kullanıcı ayrıldı: ${socket.id}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        function updateUserList() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const userList = Object.values(users).map(u => ({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    username: u.username,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            friends: u.friends,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    requests: u.requests
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            io.emit('update_users', userList);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const PORT = process.env.PORT || 3000;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            server.listen(PORT, () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                console.log(`Sunucu çalışıyor: http://localhost:${PORT}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                